import "./globals.css";

import Header from "@/components/layout/Header";
import type { Metadata } from "next";
import Navigation from "@/components/layout/Navigation";
import { Providers } from "./provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header/>
          <Navigation/>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
