import "./globals.css";

import Header from "@/components/layout/Header";
import type { Metadata } from "next";
import Navigation from "@/components/layout/Navigation";
import { Providers } from "./provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen flex flex-col">
        <Providers>
          <Header/>
          
          <div className="pt-16 flex flex-1 flex-col sm:flex-row">
            <Navigation/>
            <main className="flex-1 flex justify-center items-center">{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
